### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by vielmetti** [openalpr/openalpr#123]
I built an image with Docker under Ubuntu 14.04 using the supplied Dockerfile, and uploaded it to Docker Hub. When I run it it properly decodes plates, but every time I get the warning message

```
libdc1394 error: Failed to initialize libdc1394
```

I know the problem isn't in openalpr; I think it's either in OpenCV or somewhere in VirtualBox, based on 

http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394

but I didn't see an open Github issue for it & thus I'm opening this issue here to help identify the upstream problem (or to look for a way to work around it in the Docker build).

Repeat by:

```
% docker run vielmetti/openalpr-ubuntu
```

**Comment by vielmetti** [comment]
I switched to a CoreOS based Docker instead of boot2docker, and have the same issue.

```
Edwards-MacBook-Air:coreos-vagrant emv$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
```

**Comment by matthill** [comment]
As you're probably aware, it's an innocuous error message.  However, it does cause concern for many users (people assume they did something wrong).  There's not much we can do about it though, it's coming directly from within OpenCV.  I believe they have it fixed in the upcoming OpenCV 3.0.

I'm planning on switching over to OpenCV 3.0 as soon as possible.  Intel worked out an arrangement where IPP is now embedded in the new version of OpenCV.  Without touching the OpenALPR code, this will result in a minimum 20% speed improvement.

**Comment by hrabalvojta** [comment]
This bug is still active.
docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

**Comment by bobbytables** [comment]
Still active, anything I can help with?

**Comment by fxlae** [comment]
Still active. I'm aware that it is not a problem, but it keeps confusing people.

**Comment by AndyTsangChun** [comment]
Still active with current version in ubuntu 16.04

**Comment by douglasgalico** [comment]
I'm also seeing this issue.

**Comment by JackKuo-tw** [comment]
Still active... wait for help, Ubuntu 16.04
