### ISSUE TITLE
Provide configuration guide for C# binding

### ISSUE THREAD

**Issue by emrekenci** [openalpr/openalpr#175]
The c# binding solution under "\src\bindings\csharp" does not build out of the box.

There is a dependency on OpenCV and it needs to be explained to the user.

Here are the first steps I took to be able to build the solution:

1) Build the solution as it is downloaded. You will get the below errors:

Cannot open include file: 'opencv2/imgproc/imgproc.hpp': No such file or directory
Cannot open include file: 'opencv2/opencv.hpp': No such file or directory
Cannot open include file: 'opencv2/highgui/highgui.hpp': No such file or directory

2) Download OpenCV, extract the files. Copy the folder "build\include\opencv2" and paste it into "openalpr-master\openalpr-master\src\bindings\csharp\openalpr-net"

4) Rebuild the solution. The openalprnet-cli and openalprnet-windemo projects will not be able to locate openalpr-net.dll. Download the binaries from https://github.com/openalpr/openalpr/releases and copy the .dll file to somewhere inside your solution. Delete the old reference from the projects and add the copied file as a reference.

5) Rebuild the solution. You will get the below errors:

'openalprnet.AlprNet' does not contain a definition for 'GetVersion' ...
'openalprnet.AlprNet' does not contain a definition for 'IsLoaded' ...
'openalprnet.AlprNet' does not contain a definition for 'Recognize' ...
'openalprnet.AlprNet' does not contain a definition for 'IsLoaded'
'openalprnet.AlprNet' does not contain a definition for 'Recognize' ...

You will ALSO get the below error. 

Error	32	error LNK1104: cannot open file '..\..\..\..\windows\build\dist\2.1.0\v120\Debug\Win32\opencv_videostab248d.lib' ...

Which is where I'm stuck.

The project has a dependency on 'opencv_videostab248d.lib' but I could not find the 2.4.8 version of opencv. The latest version has a opencv_videostab300d.lib file.

I tried to find where the reference is given to replace the dependency on 2.4.8 with 3.0.0 but I could not find the reference location.

**Comment by matthill** [comment]
You shouldn't need to compile openalpr-net.cpp if you're just looking to use the library.  Do the precompiled binaries work?  There's a GUI executable in that directory that was built in C#.

**Comment by emrekenci** [comment]
Yes that's what I was hoping for. But none of the projects in the solution build.

The GUI project's executable is not included in the project. You need to build and create it but that project does not build either.

I want to be able to use the binding in my project so the executable would not be good enough for me.

**Comment by matthill** [comment]
Have you tried the following:
1. Take all the DLLs (either 64 or 32 depending on your .NET program's target) and drop them in the same folder as your .NET exe
2. Install the vc_redist installer in the binaries package
3. Reference the openalpr-net.dll in the binaries package

That has worked for me on a few different compilers/architectures.

**Comment by emrekenci** [comment]
Thanks.

Yes that's what I did at first and it seems like it will work. But I have no idea how it works so I wanted to give the samples a try :)

I'm converting the code from the samples to a clean project that is referencing the binary.

I need a sample config file. Is it ok to use this one: https://github.com/openalpr/openalpr/blob/master/config/openalpr.conf.in

**Comment by matthill** [comment]
There should be a sample openalpr.conf file in the binaries zip.  That's probably the best one to use.

**Comment by peters** [comment]
@emrekenci Have you tried https://github.com/peters/openalpr-windows ?

**Comment by peters** [comment]
To produce a working nuget package run the following command:

```
.\build.ps1 -Configuration Release -Platform x64 -Target Nupkg -PlatformToolset v120
```

**Comment by emrekenci** [comment]
@matthill Thanks for the tip. I found the config file.

Loading the binary file openalpr-net.dll is causing a runtime error that I was not able to solve:
```
Could not load file or assembly 'openalpr-net, Version=1.0.5647.40139, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```
@peters Thank you as well. Build script execution fails with this error:

```
Die : Missing cmake.exe
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:144 char:9
+         Die "Missing cmake.exe"
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Die
```
Is there any chance you could upload a working nuget package to nuget.org?

**Comment by matthill** [comment]
Usually that's because you're linking 64-bit against 32-bit or vice versa.  I've seen this when compiling a 32-bit program (on a 64-bit machine) and trying to link the 64-bit OpenALPR DLLs against it.

**Comment by peters** [comment]
@emrekenci You need to install cmake.

**Comment by emrekenci** [comment]
@matthill yes I'm running 64bit OS and I made sure I'm using the 64bit binary.

@peters Sorry. Yes installing cmake did start the build. But the build exits with this error:
```
Get-Content : Cannot find path 'C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\tesseract-ocr\
src\vs2010\libtesseract\libtesseract.vcxproj' because it does not exist.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:258 char:16
+     $Content = Get-Content $Project
+                ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\emreke...sseract.vcxproj:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Exception calling "LoadXml" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:260 char:5
+     $Xml.LoadXml($Content)
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterMethodInvoke

You cannot call a method on a null-valued expression.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:266 char:5
+     $Nodes = $Root.SelectNodes($Xpath, $NamespaceManager)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:268 char:5
+     $Properties = @{
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\tesseract-ocr\
src\vs2010\libtesseract\libtesseract.vcxproj' because it does not exist.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:258 char:16
+     $Content = Get-Content $Project
+                ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\emreke...sseract.vcxproj:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Exception calling "LoadXml" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:260 char:5
+     $Xml.LoadXml($Content)
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CatchFromBaseAdapterMethodInvoke

You cannot call a method on a null-valued expression.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:266 char:5
+     $Nodes = $Root.SelectNodes($Xpath, $NamespaceManager)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\emrekenci\Desktop\openalpr-windows-2.1.0\openalpr-windows-2.1.0\build.ps1:268 char:5
+     $Properties = @{
+     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by matthill** [comment]
Yes, but you may be compiling your .NET program in 32-bit mode, in which case using the 64-bit OpenALPR binaries will give you the error that you mentioned.

**Comment by emrekenci** [comment]
The app was targeitng Any CPU which should resolve these issues. But I made it target 64bit and got the same exception.

Could there be a mistake with the build of the .net binary? 32bit copied to 64bit folder etc?

**Comment by matthill** [comment]
Not sure if you've gotten this resolved, but I saw the exact same error message recently.  I fixed it by changing this:

![dotnet_before](https://cloud.githubusercontent.com/assets/508260/9289550/da3fca9a-4342-11e5-956b-bf67ba7b342c.png)

to this:

![dotnet_after](https://cloud.githubusercontent.com/assets/508260/9289551/dd23b334-4342-11e5-9aca-b2c0e8ec30ab.png)

**Comment by emrekenci** [comment]
@matthill thank you.

Yes I did the same and went past this error. I'm stuck at another one at the moment. I reference the "openalpr-net.dll" in my app. The .dll I'm referencing is in the folder where I have all the 64 bit binaries of openalpr. I'm able to build the code where I initialize an AlprNet object. But at runtime, I get this error: " Could not load file or assembly 'openalpr-net, Version=1.0.5647.40139".

The demo app that comes with the binaries, openalprnet-windemo.exe, is launching but when I try to get it to detect a license plate, it says "Error initializing OpenALPR"

I have Visual C++ installed on this machine but a later version than the one you included the setup for in the binaries.

**Comment by matthill** [comment]
You may get more responses on the forum.  I ran through this recently on using VS 2010 to compile and then VS 2015 to run my .NET app and everything worked fine.

**Comment by darkbcd** [comment]
@matthill  I have the same issue that everyone has posted here but I'm building a WCF Web Sevice and I'm referencing the 64bit assembly but I still having the same error message I know all ready how to fix this kind of message in other projects but in this case even with the forced 64 bit compilation and enabling 64 and 32 bit applications in the IIS Application Pools nothing was turning out in the way I've expected. But for Windows Applications there is no such issue I'm running well the only bad situation is on ASP.NET with WCF Web Services.
![image](https://cloud.githubusercontent.com/assets/4265764/13377569/795015f6-dda6-11e5-8d1c-f5561f54f743.png)

![image](https://cloud.githubusercontent.com/assets/4265764/13377574/9df8472a-dda6-11e5-9617-14637387414d.png)

![image](https://cloud.githubusercontent.com/assets/4265764/13377581/af362610-dda6-11e5-81fa-f90270268162.png)

**Comment by MhmdAlmz** [comment]
I have same issue,
I update the build.ps1 folder ...
`line 13 from [ValidateSet("v100", "v110", "v120", "v140")]  to [ValidateSet("v100", "v110", "v120", "v140", "v150")]`

After than 
I add too script v150
```

        "v150" {
            $script:ToolsVersion = "15.0"
            $script:VisualStudioVersion = "15.0"
            $script:VXXCommonTools = $env:VS150COMNTOOLS 
            $script:CmakeGenerator = "Visual Studio 15 2017"
        }
```
I added the Enviroment Path and update this code 
 from 
```
  $script:VXXCommonTools = Join-Path $VXXCommonTools  "..\..\vc"
    if ($VXXCommonTools -eq $null -or (-not (Test-Path($VXXCommonTools)))) {
        Die "Error unable to find any visual studio environment"
    }
```
to 
`  $script:VXXCommonTools = Join-Path $VXXCommonTools  "..\..\vc\Auxiliary\Build"
    if ($VXXCommonTools -eq $null -or (-not (Test-Path($VXXCommonTools)))) {
        Die "Error unable to find any visual studio environment"
    }`

So , when i run this code i get this error.

```
PS C:\WINDOWS\system32\openalpr\windows> .\build.ps1 -Configuration Release -Platform x64 -Target Nupkg -PlatformToolset
 v150
```

Error ;
```

PlatformToolset: Successfully configured msvs PlatformToolset v150


Die : Missing cmake.exe
At C:\WINDOWS\system32\openalpr\windows\build.ps1:144 char:9
+         Die "Missing cmake.exe"
+         ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Die
```
@emrekenci , did you solve it ?
